"use client";
import { FormEvent, useState } from "react";
import { useOrderRooms } from "@/components/order-room-provider";

export default function NewTeamPage() {
  const { createTeam } = useOrderRooms();
  const [teamName, setTeamName] = useState("");
  const [members, setMembers] = useState<string[]>([]);
  const [newMember, setNewMember] = useState("");
  const [creator, setCreator] = useState("");
  const [error, setError] = useState("");
  const addMember = () => { const name = newMember.trim(); if (!name) return setError("추가할 팀원의 이름을 입력해 주세요."); if (members.some((member) => member.toLowerCase() === name.toLowerCase())) return setError("같은 이름은 한 팀에 한 번만 등록할 수 있어요."); const next = [...members, name]; setMembers(next); setNewMember(""); setError(""); };
  const removeMember = (name: string) => { const next = members.filter((item) => item !== name); setMembers(next); if (creator === name) setCreator(""); };
  const create = async (event: FormEvent) => { event.preventDefault(); if (!teamName.trim()) return setError("팀 이름을 입력해 주세요."); if (members.length === 0) return setError("팀원을 최소 1명 추가해 주세요."); if (!creator) return setError("나는 누구인지 선택해 주세요."); try { const teamCode = await createTeam(teamName.trim(), members, creator); window.location.assign(`/team/${teamCode}`); } catch (value) { setError(value instanceof Error ? value.message : "팀을 만들지 못했습니다."); } };
  return <main className="mx-auto min-h-screen max-w-xl p-5"><p className="text-sm font-bold text-amber-700">NEW TEAM</p><h1 className="mt-2 text-3xl font-black tracking-tight">우리 팀을 만들어볼까요?</h1><form onSubmit={create} className="mt-7 space-y-7"><label className="block"><span className="mb-2 block text-sm font-bold">팀 이름</span><input required value={teamName} onChange={(event) => setTeamName(event.target.value)} placeholder="예: 카드디자인팀" className="w-full rounded-2xl border border-stone-200 bg-white px-4 py-3.5" /></label><section><p className="mb-2 text-sm font-bold">팀원</p>{members.length === 0 ? <p className="rounded-2xl border border-dashed border-stone-300 bg-white px-4 py-5 text-center text-sm text-stone-500">등록된 팀원이 없습니다.</p> : <div className="space-y-2">{members.map((member) => <div key={member} className="flex justify-between rounded-2xl border border-stone-200 bg-white px-4 py-3"><b>{member}</b><button type="button" onClick={() => removeMember(member)} className="text-sm text-rose-500">삭제</button></div>)}</div>}<div className="mt-3 flex gap-2"><input value={newMember} onChange={(event) => setNewMember(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); addMember(); } }} placeholder="팀원 이름" className="min-w-0 flex-1 rounded-2xl border border-stone-200 bg-white px-4 py-3" /><button type="button" onClick={addMember} className="rounded-2xl bg-stone-200 px-4 text-sm font-bold">+ 팀원 추가</button></div></section><label className="block"><span className="mb-2 block text-sm font-bold">나는 누구인가요?</span><select value={creator} onChange={(event) => setCreator(event.target.value)} disabled={members.length === 0} className="w-full rounded-2xl border border-stone-200 bg-white px-4 py-3.5 disabled:bg-stone-100"><option value="">직접 선택해 주세요</option>{members.map((member) => <option key={member} value={member}>{member}</option>)}</select></label>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button type="submit" className="w-full rounded-2xl bg-amber-600 py-4 font-extrabold text-white">팀 만들기</button></form></main>;
}
