"use client";
import { use, useEffect } from "react";
import Link from "next/link";
import { AppHeader } from "@/components/app-header";
import { OrderRoomCard } from "@/components/order-room-card";
import { ShareOrderActions } from "@/components/share-order-actions";
import { useOrderRooms } from "@/components/order-room-provider";
import { UserSelector } from "@/components/user-selector";
export default function TeamPage({ params }: { params: Promise<{ teamCode: string }> }) { const { teamCode } = use(params); const { currentUser, ready, rooms, teams, activateTeam, getTeamMembers } = useOrderRooms(); const team = teams.find((item) => item.code === teamCode); useEffect(() => { if (team) activateTeam(teamCode); }, [activateTeam, team, teamCode]); if (!ready) return null; if (!team) return <main className="mx-auto max-w-xl p-8">팀을 찾을 수 없어요. 이 프로토타입에서 새 팀을 만들어보세요.</main>; const members = getTeamMembers(team.id); if (!currentUser) return <UserSelector teamCode={teamCode} teamName={team.name} members={members} />; const orders = rooms.filter((order) => order.teamId === team.id); return <main className="mx-auto min-h-screen max-w-xl p-5 pb-12"><AppHeader teamCode={teamCode} /><section className="mb-6"><p className="text-sm font-bold text-amber-700">TEAM · {team.code}</p><h1 className="mt-1 text-3xl font-black tracking-tight">{team.name}</h1><p className="mt-2 text-sm text-stone-500">{members.length}명 · {currentUser.name}으로 사용 중</p><ShareOrderActions title={`${team.name} 커피방에 참여하세요 ☕`} /></section><section className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-black">오늘의 주문</h2><p className="mt-1 text-sm text-stone-500">같은 날에도 여러 주문을 만들 수 있어요.</p></div><Link href={`/team/${teamCode}/order/new`} className="rounded-2xl bg-stone-800 px-4 py-3 text-sm font-bold text-white">+ 새 주문 만들기</Link></section><section className="space-y-3">{orders.map((order) => <OrderRoomCard key={order.id} room={order} teamCode={teamCode} />)}</section></main>; }
